Repository kylomite/futbol, pull requests merged in 2024-08, with the labels that each got.

#42 Feat/percentage ties
  lib/stat_tracker.rb
  spec/spec_helper.rb
  spec/stat_tracker_spec.rb
Labels: PR

#43 Feat/lowest total score
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: game, PR

#44 Feat/average goals per game
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: game, PR

#45 Feat/highest scoring visitor
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: league, PR

#48 Feat/least accurate team
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: season, PR

#52 Feat/count of teams
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: league, PR

#54 Feat/fewest tackles
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: season, PR

#60 Feat/#count of games by season
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: game, PR

#61 Feat/average goals by season
  lib/game.rb
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: game, PR

#58 feat: add percentage_visitor_wins method & test
  lib/stat_tracker.rb
  runner.rb
  spec/stat_tracker_spec.rb
Labels: game, PR

#59 Feat/worst offense
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: league, PR

#64 Feat/highest scoring home team
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: league, PR

#65 Feat/#most accurate team
  lib/stat_tracker.rb
  runner.rb
  spec/stat_tracker_spec.rb
Labels: season, PR

#70 Feat/winningest coach
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: season, PR

#68 refactor: least_accurate_team to use helper methods
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: PR

#69 refactor: highest_scoring_visitor to use helper methods
  lib/stat_tracker.rb
Labels: PR

#71 Feat/most tackles
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: season, PR

#73 Update/readme
  README.md
Labels: PR

#74 Test: added win_loss_ratio test
  spec/stat_tracker_spec.rb
Labels: PR
